version: '3.8'
services:
  pivproxy:
    build: .
    ports:
    - "4443:4443"
    volumes:
    - $PWD/secrets:/secrets
    environment:
      PROXY_NAME: localhost
      PROXY_URL: http://app/
      #PROXY_ALL_USERS: 'true'
      PROXY_USERS: '"UID=47001003358691+CN=TIMOTHY SPENCER,OU=General Services Administration,O=U.S. Government,C=US", "XXX"'
  app:
    image: logindotgov/pretend-app
    ports:
    - "80:80"

